[package]
name = "the_rust_supper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://stackoverflow.com/questions/72028861/use-of-undeclared-crate-or-module
generic-array = "1.0.0"